export const trainTemplate = {
	TrainId: "",
	CurrentBlock: 1,
	PreviousBlock : 0,
	RouteIndex: 0,
	Route: [],
	Stations: [],
	DepartureTime: "12:00",
	Line: "green",

	Acceleration: 0,
	AccelerationLimit: 5,
	AnyFailures: false,
	BlockAuthority : 0,
	BlockLength : 50,
	BrakeFailure: false,
	CommandedPower : 0,
	DecelerationLimit: -5,
	DoorStatus: false,
	EBrakeStatus: false,
	EDoorStatus: false,
	EngineFailure: false,
	ExternalLightState: false,
	ExternalTemperature: 70,
	Grade : 0,
	Height: 12,
	InternalLightState: false,
	InternalTemperature: 70,
	LeftDoorStatus: false,
	Length: 300,
	LightState : false,
  Line : "GreenLine",
	ManualMode: false,
	Mass: 277817,
	Passengers: 0,
	Position : 0,
	Power: 0,
	RightDoorStatus: false,
	SBrakeStatus: false,
	SetpointSpeed: 0,
	SignalFailure: false,
	SpeedLimit: 45,
	Velocity: 0,
	Width: 10,

	Kp: 35,
	Ki: 1,
	uk: 0,
	ukm1: 0,
	ek: 0,
	ekm1: 0,
}